[project]
name = "snake-game"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Connor", email = "connor@localhost" }
]
requires-python = ">=3.10"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
snake-game = "snake_game:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
